steps:
  # 建構 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kripto-saat-flash:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kripto-saat-flash:latest'
      - '.'

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/kripto-saat-flash:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/kripto-saat-flash:latest'

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kripto-saat-flash'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kripto-saat-flash:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/kripto-saat-flash:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/kripto-saat-flash:latest' 